services:
  backend:
    image: asia-south1-docker.pkg.dev/gentle-scene-466610-a2/online-learning-portal/backend:latest
    container_name: online-learning-backend
    env_file:
      - ./Backend/.env
    ports:
      - "3000:3000"
    networks:
      - online-learning-network
    restart: unless-stopped
    volumes:
      - ./Backend/uploads:/app/uploads
    depends_on:
      - cloudsql-proxy
    environment:
      # Override DB host to point to proxy
      DB_HOST: 34.180.0.12
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: Devanshu@2005
      DB_NAME: postgres
      INSTANCE_CONNECTION_NAME: gentle-scene-466610-a2:asia-south1:online-learning-portal-postgres-db
      PROJECT_ID: gentle-scene-466610-a2
      BUCKET_NAME: upload-study-material
      KEYFILENAME: ./gentle-scene-466610-a2-1436aaba1c89.json
      BACKEND__PRODUCTION_URL: http://34.47.136.4:3000
      FRONTEND_PRODUCTION_URL: http://edu.onthegoalways.com 
      FRONTEND_LOCALHOST_URL: http://localhost:5173
      BACKEND__LOCALHOST_URL: http://localhost:3000
      

  frontend:
    image: asia-south1-docker.pkg.dev/gentle-scene-466610-a2/online-learning-portal/frontend:latest
    container_name: online-learning-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - online-learning-network
    restart: unless-stopped
    environment:
      # Use backend service name (not localhost)
      VITE_BACKEND_URL: https://edu.onthegoalways.com/api

  cloudsql-proxy:
    image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.8.0
    container_name: cloudsql-proxy
    command: >
      --address=0.0.0.0
      --port=5432
      --instance=gentle-scene-466610-a2:asia-south1:online-learning-portal-postgres-db
    ports:
      - "5432:5432"
    volumes:
      - ./gentle-scene-466610-a2-1436aaba1c89.json:/config/key.json:ro
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: ./gentle-scene-466610-a2-1436aaba1c89.json
    restart: unless-stopped
    networks:
      - online-learning-network

networks:
  online-learning-network:
    driver: bridge